

reggae ::= message | ('[' message (',' message)* ']')

message ::= '[' (('msg' ',' title ',' msg_content ) |
  ( ('url' | 'urls')  ',' '[' url_spec ( ',' url_spec)* ']' ) |
  (('row' | 'rows') ',' row_spec ',' '[' row_values (',' row_values)* ']' ) |
  (('error' | 'errors') ',' '[' err_spec (',' err_spec)* ']' )) ']'

title ::= string_value

msg_content ::= string_value 

url_spec ::= '[' url ',' title ',' desc ']'

desc ::= text_value





row_format ::= '""' | '[' col_spec (',' col_spec)* ']'

col_spec ::= '[' name ',' type ',' restrictions ']'

name ::= string_value

type ::= "text" | "number" | "datetime" | "bool" | "rows"

restrictions ::= '[' restriction (',' restriction) ']'

restriction ::= "ro" | "required" | range | permitted_values | pattern




