

reggae ::= message | ('[' message (',' message)* ']')

message ::= '[' (('mesg' ',' title ',' mesg_content ) |
  ( 'url' ',' url ',' title ',' description  ) |
  (('row' | 'rows') ',' row_spec ',' '[' row_values (',' row_values)* ']' ) |
  ('error' ','  '[' err_spec (',' err_spec)*  ']')) ']'

title ::= string_value

mesg_content ::= string_value 

url ::= url_value

description ::= string_value

desc ::= text_value

row_spec ::= '[' (flgs ',')? col_spec (',' col_spec)* ']'

flgs ::= int_value

col_spec ::= '[' name ',' type ',' restrictions ']'

err_spec ::= '[' col ',' err ']'

name ::= string_value

col ::= string_value

err ::= string_value

type ::= "text" | "int" | "fixed" | "email" | "password" | "date" | "time" | "datetime" | "bool" | "rows"

restrictions ::= '[' restriction (',' restriction) ']'

restriction ::= "ro" | "required" | min | max | permitted_values | pattern

min ::= '[' 'min' ',' min_value ']'

max ::= '[' 'max' ',' max_value ']'

permitted_values ::= '[' 'values' ',' value (',' value)* ']'

pattern ::= regex_value


